### ISSUE TITLE
[BUG] installation issues with numpy < 1.23

### ISSUE THREAD

**Issue by sconstable** [joshlk/k-means-constrained#30]
**Describe the bug**
While`k-means-constrained` claims to support `numpy>=1.22.0` in `setup.py`, actually attempting to install and use it results in an error related to the numpy API version:
```
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import k_means_constrained
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sconstable/local-dev/venv/lib/python3.10/site-packages/k_means_constrained/__init__.py", line 4, in <module>
    from .k_means_constrained_ import KMeansConstrained
  File "/home/sconstable/local-dev/venv/lib/python3.10/site-packages/k_means_constrained/k_means_constrained_.py", line 18, in <module>
    from .sklearn_import.metrics.pairwise import euclidean_distances
  File "/home/sconstable/local-dev/venv/lib/python3.10/site-packages/k_means_constrained/sklearn_import/metrics/pairwise.py", line 10, in <module>
    from k_means_constrained.sklearn_import.metrics.pairwise_fast import _sparse_manhattan
  File "k_means_constrained/sklearn_import/metrics/pairwise_fast.pyx", line 26, in init k_means_constrained.sklearn_import.metrics.pairwise_fast
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Minimum working example**
The following Dockerfile is enough to reproduce the issue for me:
```
from ubuntu:20.04
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install numpy==1.22.4 k-means-constrained
RUN python3 -c 'import k_means_constrained'
```

**Versions:**
- Python:  3.8, 3.10
- Operating system: [Windows/MacOS/Linux] Ubuntu 20.04, 22.04
- k-means-constrained: 0.7.1
- numpy: 1.22.4
- scipy: 1.9.0
- ortools: 9.0.9048
- joblib: 1.1.0
- cython (if installed): 0.29.32

**Comment by lucamagnasco** [comment]
It happened also to me with mac monterrey and Python 3.9.7

**Comment by sconstable** [comment]
the confusion has been resolved, `k-means-constrained` officially requires `numpy>=1.23.0` now. thanks!
