### ISSUE TITLE
Maybe tag a new release?

### ISSUE THREAD

**Issue by amks1** [joshlk/k-means-constrained#40]
I'm getting the following build error while doing a `pip install` after upgrading to Python 3.11.

```
Downloading k_means_constrained-0.3.3.tar.gz (369 kB)
     â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”�â”� 369.8/369.8 kB 38.7 MB/s eta 0:00:00      
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  Ã— python setup.py egg_info did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h7ivomt8/k-means-constrained_9e6bbb958901423eb92830efe879d106/setup.py", line 9, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'   
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Ã— Encountered error while generating package metadata.
â•°â”€> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

From your source code I see that you fixed this issue using a `try .. except` block, and I was able to install the package by specifying the constraint
```
k-means-constrained @ git+https://github.com/joshlk/k-means-constrained.git@master#egg=k_means_constrained
```

Do create a new tag with the changes, so that they're pulled when people do a simple `pip install`. :)

**Comment by joshlk** [comment]
Hi Amks1!

I made those changes to the build process quite a while ago and they will have been included in the latest release. Are you sure you were trying to install the latest release before? Can you send the details of how you were previously installing k-means-constrained and what version you were trying to install? Also the version details of:
Python:
Operating system: [Windows/MacOS/Linux]

Thanks,
Josh
