### ISSUE TITLE
Cannot install on Docker

### ISSUE THREAD

**Issue by ismail-khan-tajir** [joshlk/k-means-constrained#5]
### Background

I have the following Dockerfile:

```
FROM python:3.7

ADD requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

ADD . /app

CMD gunicorn -b :$PORT main:app --timeout 60
```

My `requirements.txt` file contains `k-means-constrained==0.3.3`.

### Problem

I get the following error on the add-requirements step:

```
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-08ldu34e/k-means-constrained/setup.py'"'"'; __file__='"'"'/tmp/pip-install-08ldu34e/k-means-constrained/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zj209e8i
         cwd: /tmp/pip-install-08ldu34e/k-means-constrained/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-08ldu34e/k-means-constrained/setup.py", line 9, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install -r /app/requirements.txt' returned a non-zero code: 1
ERROR
```

### Attempted solutions
- Changed base image to python:3.7, but got the same result. So the base image is not the problem.
- Added `Cython` to `requirements.txt` above `k-means-constrained`, but still no luck.

**Comment by ismail-khan-tajir** [comment]
Solution found: add `RUN pip install Cython numpy` to the Dockerfile, before `requirements.txt` is installed.

This is still just a workaround. I think the problem lies in the fact that neither `Cython` nor `numpy` is listed in the package's `requirements.txt`.

**Comment by joshlk** [comment]
Hi,

Thanks for taking the time and issuing a bug ticket. If you use the latest version (0.4.2) from PyPi the problem should be fixed.

Let me know how it goes.

Josh

**Comment by joshlk** [comment]
Closing due to inactivity. Please comment if you have an issue.
